### ISSUE TITLE
undefined index name

### ISSUE THREAD

**Issue by joernroeder** [bnomei/kirby3-autoid#16]
i'm getting the following error in the response of my page after updating to the latest version (as well as latest kirby).

```
{"status":"error","exception":"Whoops\\Exception\\ErrorException","message":"Undefined index: name","file":"endor\/bnomei\/kirby3-autoid\/classes\/AutoID.php","line":178,"code":8}
```

ping me on slack if you want to see the request i'm sending ;)

**Comment by bnomei** [comment]
fixed in https://github.com/bnomei/kirby3-autoid/releases/tag/v1.2.4
