### ISSUE TITLE
Not working with date.handler strftime

### ISSUE THREAD

**Issue by movingwater** [bnomei/kirby3-autoid#19]
If I have set my config to `'date.handler' => 'strftime',` the plugin is not working. It gives an error:
````
Argument 6 passed to Bnomei\AutoID::commitEntry() must be of the type integer or null, string given, called in ../www/site/plugins/kirby3-autoid/classes/AutoID.php on line 186
````

Is there a way to use it with strftime?

**Comment by bnomei** [comment]
i will take a look at this later today. thanks for reporting this issue

**Comment by bnomei** [comment]
https://forum.getkirby.com/t/how-to-handle-the-date-handler-option-in-plugins-using-date-modified/12504

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-autoid/releases/tag/v.1.2.5
