### ISSUE TITLE
autoid for users

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-autoid#23]

**Comment by neildaniels** [comment]
Is this actually necessary? Kirby already creates persistent IDs for users.

https://github.com/getkirby/kirby/blob/80b69380e672565a849037232c9951d1e32774c8/src/Cms/User.php#L127-L136

https://github.com/getkirby/kirby/blob/80b69380e672565a849037232c9951d1e32774c8/src/Cms/UserActions.php#L207-L223

**Comment by bnomei** [comment]
@neildaniels i will take another look to make sure i fully understand whats possible with the core  user ID asap.

the general idea was to find users with the optimized lookup table just like pages, files and structures. the user is just the last basic object kirby which autoid does not support yet. *an single ID lookup for all core objects* if you want. but only if one would have thousands of users it would make sense so i did not add this sooner.
