### ISSUE TITLE
Drafts aren't included

### ISSUE THREAD

**Issue by shoogstoel** [bnomei/kirby3-autoid#27]
I'm not sure if it's an oversight or on purpose, but the plugin doesn't include drafts.
The initial indexing can be solved simply by using the index option you provide, like so:

```
'bnomei.autoid.index' => function ():\Kirby\Cms\Pages {
  return kirby()->site()->childrenAndDrafts()->index();
}
```

However, the `find` function uses Kirby's `page` helper function, which doesn't include drafts either. A simply fix would be to replace it with `App::instance()->site()->findPageOrDraft()`.

If it is indeed on purpose. How do you feel about an option to include drafts?

**Comment by bnomei** [comment]
let's see what the community has to say...
https://forum.getkirby.com/t/poll-autoid-plugin-with-or-without-indexing-drafts/13945

**Comment by jesuismaxime** [comment]
@shoogstoel do you have a usecase/exemple on how/why you need to assign an `autoid` to a draft? Technically drafts aren't supposed to be listed/unlisted, so aren't supposed to be "findable" or indexed.

Will wait for an answer before vote/downvote

**Comment by shoogstoel** [comment]
@jesuismaxime sorry for the late response.
In our specific case we built a global media library (each media collection is a page) which can be used throughout the whole page. These pages never leave the draft status (since they aren't real pages).
I realize that this is somewhat of an edge case since we used the pages for something they aren't meant to be.

**Comment by bnomei** [comment]
@shoogstoel i do not understand why the global media library need to be drafts. 

you would have to manually exclude it from sitemap plugin, feeds, use a routes with wildcard with same name to remove direct access and some minor other stuff concering public media folder (see kirby docs: asset firewall).
