### ISSUE TITLE
Duplicate autoid ?

### ISSUE THREAD

**Issue by tristantbg** [bnomei/kirby3-autoid#28]
I got a duplicate AutoID on two pages (they had the same one), is it possible ?
Does the plugin checks if the autoid already exists or not ?

**Comment by bnomei** [comment]
should almost not be possible. it generates very random values by default
https://github.com/bnomei/kirby3-autoid/blob/master/classes/AutoID.php#L395

and has a loop to make sure that values is not used yet
https://github.com/bnomei/kirby3-autoid/blob/master/classes/AutoID.php#L410
https://github.com/bnomei/kirby3-autoid/blob/master/index.php#L12

**question**
any chance the content file was copied on file-system level?

**Comment by tristantbg** [comment]
Thank you for the explanations !

**Comment by bnomei** [comment]
mayberelated to new k 3.2.0 duplcate feature? see #30
