### ISSUE TITLE
Support for nested structures?

### ISSUE THREAD

**Issue by kgevaert** [bnomei/kirby3-autoid#29]
Hi,
this is a great plugin. But it seems not to work for nested structures. Maybe this could be added?

**Comment by bnomei** [comment]
yeah i had a code TODO remoder for that but never found the time to add it.

just out of curiosity how deep to you nest your structures?

**Comment by kgevaert** [comment]
Hi,

In my cases it's only 1 level deep. A structure in a structure.

thanks

Op do 13 jun. 2019 om 12:43 schreef Bruno Meilick <notifications@github.com
