### ISSUE TITLE
New duplicate function (Kirby 3.2.0)

### ISSUE THREAD

**Issue by tristantbg** [bnomei/kirby3-autoid#30]
How will you handle this new functionality ? Maybe by checking after the page.create hook ?

Thanks.

**Comment by bnomei** [comment]
afaik the hook of the new page should be triggered by kirbys core and autoid continue working as intended. i did not have the time to test this yet. did you experience any issues in that regard?

**Comment by bnomei** [comment]
oh i get it now. the autoid field value will be duplicated. i will think about a solution.

**Comment by bnomei** [comment]
https://forum.getkirby.com/t/how-not-to-duplicate-all-fields/14748

**Comment by tristantbg** [comment]
On `page:create` you can remove the field autoID if there is one ? And then create it ?
