### ISSUE TITLE
Feature Request: Nano ID generator

### ISSUE THREAD

**Issue by pReya** [bnomei/kirby3-autoid#38]
Thanks for the work! I'd really like to have a generator implementation based on [nanoid](https://github.com/ai/nanoid). It's an amazing ID generator, which is in many cases faster than uuid and also uses a larger alphabet, so nanoids can be shorter than uuids. There's already a [nanoid implementation in PHP](https://github.com/hidehalo/nanoid-php). Since you used interfaces, this should be quite easy. I'm not a PHP developer, but if you like the feature idea, I might take the time to sit down and try to implement it in PHP.

**Comment by bnomei** [comment]
done. https://github.com/bnomei/kirby3-autoid/releases/tag/v2.1.1

**Comment by bnomei** [comment]
you need to adjust you site/config/config.php file like this...

```php
return [
    'bnomei.autoid.generator' => function () {
        return (new \Bnomei\NanoGenerator())->generate();
    },
    // ... other options
];
```
