### ISSUE TITLE
Multilanguage Setup doesn't create different Auto Ids

### ISSUE THREAD

**Issue by chrispreisler** [bnomei/kirby3-autoid#44]
Hey guys,

I have a multilanguage Setup with two languages: DE and EN.  EN ist the default language.

When I create a new page with the default language active and save the default language content file ist added an auto id. When I then switch the language and fill in content with the german laugage active and hit save, it saves the same auto id of the default language into the german content file.

When I first create the page in the German language and then translate everything in the English language everything works as expected and every language gets its own auto id.

Is this a bug?

Thank you very much for your help.

Best regards
Chris

**Comment by bnomei** [comment]
did you setup the autoid field as [non-translatable](https://github.com/bnomei/kirby3-autoid/wiki/Setup:-Blueprints)? alternatively you could use the `type: autoid`.

**Comment by bnomei** [comment]
but maybe its related to https://github.com/bnomei/kirby3-autoid/issues/22 as well. i need to investigate again what happens if non default languages are used to create pages and how the autoid behaves post next page saves.

**Comment by chrispreisler** [comment]
Thanks for your reply. I also thought, that it is maybe related to it. I integrate the autoID like this in the Blueprint:

```
autoid:
    type: hidden
```

**Comment by bnomei** [comment]
i multilanguage setups you need
```
autoid:
    type: hidden
    translate: false
```

**Comment by chrispreisler** [comment]
Thanks, but I want different ids for differnt languages.

**Comment by bnomei** [comment]
ah i see. that is currently not possible.i currently search the page data stored in the lookup table and find that same page and retrieve that id. this is necessary to ensure that only one id per page exists. i could add the language into the data stored... but i am not sure yet if this would be a breaking change (meaning new major version).

i have a fews multilang setups as well but never needed that. why do you need different ids? can you explain that usecase a bit more?
