### ISSUE TITLE
Support custom field name instead of `autoid`

### ISSUE THREAD

**Issue by afbora** [bnomei/kirby3-autoid#45]
I would expect it to support different field name when `type: autoid` is used, like that:

````yaml
 uuid:
    type: autoid
````

**Comment by bnomei** [comment]
the custom field was created to skip creating non-translatable, disabled fields over and over again.

agreed its possible in code to make the name of the field optional. but it that would make consistent documentation of plugin very hard and i expect it to be used very rarely. 

so i will not do that (for now). if anyone needs it please upvote and explain why.
