### ISSUE TITLE
Kirby 3.4 support: `page.duplicate:after` doesn't provide `$newPage` argument

### ISSUE THREAD

**Issue by johannschopplich** [bnomei/kirby3-autoid#46]
I just ran @lukasbestle's [migration checker plugin](https://gist.github.com/lukasbestle/6a7d2d89448b096ad49404aac0b17d8f) and got the following error: 

```
kirby3-autoid/index.php:156 (page.duplicate:after)
‼️ The page.duplicate:after event does not provide the $newPage argument.
```

I guess that's an easy fix. Thanks in advance!

**Comment by bnomei** [comment]
will be fixed in 2.7.0.

but @lukasbestle needs to update the checker since it should be `$duplicatePage`.
https://github.com/getkirby/kirby/blob/dbd7fa7f303e7045626adb72c5f0b29c6ccadb44/src/Cms/PageActions.php#L332
https://getkirby.com/docs/reference/plugins/hooks/page-duplicate-after

**Comment by lukasbestle** [comment]
@bnomei What needs to be updated? The checker already checks for `$duplicatePage`.

**Comment by bnomei** [comment]
@lukasbestle i was just refering to the error message @johannschopplich provided and `$newPage` is the varname requested by the migration checker.

```‼️ The page.duplicate:after event does not provide the $newPage argument.```

**Comment by lukasbestle** [comment]
No, `$newPage` was the variable name used in your plugin that does *not* exist in 3.4.0.

**Comment by bnomei** [comment]
Thanks. I missunderstodd the error message then... I somehow expected the helper to tell me what to do and how to fix it and not just the place i messed up but not further assistance.

**Comment by lukasbestle** [comment]
The error message contains a link to the respective reference page in the HTML output.

But I will update the checker to also print the expected name.

**Comment by lukasbestle** [comment]
@bnomei The hook migration checker is now updated.

<img width="800" alt="Screenshot of the updated migration checker" src="https://user-images.githubusercontent.com/1595007/87076822-8f797600-c222-11ea-99cc-fc19dd1377e3.png">
