### ISSUE TITLE
autoid plugin in pagetable plugin

### ISSUE THREAD

**Issue by favger** [bnomei/kirby3-autoid#47]
Hello,

How can I convert auto id as name in Page Table plugin?

![autoid-to-name](https://user-images.githubusercontent.com/25633595/87253830-ea130c00-c486-11ea-925e-275de7d2b831.png)

**Comment by bnomei** [comment]
the pagestable plugin lets you [configure the text](https://github.com/sylvainjule/kirby-pagetable#4-column-options).

## single value in field
use [fromAutoID helper](https://github.com/bnomei/kirby3-autoid/wiki/PHP:-autoid(),-Field-Method-fromAutoID()#find-pagefile-object-in-php)
```yml
text: '{{ page.yourfieldname.fromAutoID.title }}'
```

## multiple values in field
based the screenshots you use a multiselect field and not just a single value. i do not think this can be solved with just the query language. you need [an additional fieldmethod](https://getkirby.com/docs/reference/plugins/extensions/field-methods).

```yml
text: '{{ page.yourfieldname.fromAutoIDToMultipleTitles }}'
```

**site/plugins/autoid-multiselect/index.php**
```php
<?php
Kirby::plugin('your/plugin', [
    'fieldMethods' => [
        'fromAutoIDToMultipleTitles' => function ($field) {
            return implode(', ', array_map(function($value) {
                $page = autoid($value);
                 return $page ? $page->title()->value() : '';
            }, $field->split()));
        }
    ]
]);
```
> NOTE: untested but it should get you a point to start your own implementation

**Comment by bnomei** [comment]
and sorry i responded so late 😊

**Comment by favger** [comment]
@bnomei This solution worked very well for me. Thank you very much for your support.
