### ISSUE TITLE
searchForTemplate() returns Kirby\Cms\Collection instead of Kirby\Cms\Pages

### ISSUE THREAD

**Issue by iskrisis** [bnomei/kirby3-autoid#80]
I thought the use of `Collection` instead of `Pages` was because of handling of drafts. It seems the `searchForTemplate` gathers drafts but they are null in the collection anyway. The problem with collection is that you cant use `listed`/`unlisted` and some other methods.

https://github.com/bnomei/kirby3-autoid/blob/76372d3b8d6bab5f4c7188944f48e54f9eb33b51/classes/AutoIDDatabase.php#L111-L116

Change could just be
```php
$results = new \Kirby\Cms\Pages;
$str = "SELECT * FROM AUTOID WHERE template = '${template}'" . $rootId;
foreach ($this->database->query($str) as $obj) {
	$results->add((new AutoIDItem($obj))->toObject());
}
return $results;
```
Not sure how Drafts should be handled - `Kirby\Cms\Pages` seem to be really pesky about including drafts because they have no id. But i think the returned object from `searchByTemplate`/`findByTemplate` should be `Kirby\Cms\Pages`.

**Comment by iskrisis** [comment]
@bnomei i would PR this (i mean its in the comment) just don't know your opinion about this. Sorry i didn't want to bring you more work.

**Comment by bnomei** [comment]
i will probably take a look next week. no problem
